### ISSUE TITLE
UltrawideMania not working in Plus version.

### ISSUE THREAD

**Issue by Wolfydev** [Rubberduckycooly/RSDKv5-Example-Mods#20]
Uploading SVID_20240808_194403_1 (1).mp4…

**Comment by Wolfydev** [comment]
https://github.com/user-attachments/assets/2fdd7b1d-b4bd-45db-8174-be816b166618

**Comment by MegAmi24** [comment]
Make sure the mod is enabled in the mods menu. If it gets automatically disabled when trying to load the mod in-game, then that means the mod binary does not exist or is built incorrectly; you'll have to [rebuild the decomp with the mod included](https://github.com/MegAmi24/Mania-Decomp-Mods/blob/main/BUILDING.md).

**Comment by Eggmanplant** [comment]
The version of RSDK here is very old. Did you build from source or instead download from a YouTube comment or description?
